FROM python:3.13-slim

WORKDIR /app

COPY /src/main.py /app
COPY /src/tictactoe.py /app
COPY /src/gif.py /app
COPY /src/server.py /app

COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["python", "main.py"]
