FROM python:3.13-slim

WORKDIR /app

COPY /src/*.py /app/
COPY data/quotes.txt /app/data/quotes.txt
COPY requirements.txt /app
COPY *.env /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["python", "main.py"]
